name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --experimental-vm-modules --experimental-import-meta-resolve
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'
          cache: 'yarn'

      # TODO: ESM/CommonJSの互換性の問題により完全なyarn installは一時的にコメントアウト
      # - run: yarn install --frozen-lockfile
      # - run: npx playwright install --with-deps
      # - uses: nrwl/nx-set-shas@v4
      # - run: npx nx affected -t lint test build e2e
